{% set name = "luv" %}
{% set version = "1.44.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/luvit/{{ name }}/archive/{{ version }}-1.tar.gz
  sha256: f8c69908e17ec8ab370253d1508e23deaecfc0c4752d2efb77e427e579501104


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - lua-compat-5.3-c
    - make
  host:
    - libuv
    - luajit-openresty
  run:
    - libuv

test:
  commands:
    - test -f $PREFIX/lib/libluv${SHLIB_EXT}

about:
  home: https://github.com/luvit/{{ name }}
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Bare libuv bindings for lua
  dev_url: https://github.com/luvit/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
