context:
  version: 1.48.0

package:
  name: luv
  version: ${{ version }}

source:
  url: https://github.com/luvit/luv/archive/${{ version }}-2.tar.gz
  sha256: e64cd8a0197449288b37df6ca058120e8d2308fc305f543162b5bf3e92273a05

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake
    - lua-compat-5.3-c
    - if: unix
      then: make
    - if: win
      then: ninja
  host:
    - libuv
    - luajit-openresty
  run:
    - if: win
      then: luajit-openresty
  run_exports:
    - ${{ pin_subpackage('luv', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libluv${SHLIB_EXT}

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Bare libuv bindings for lua
  homepage: https://github.com/luvit/luv
  repository: https://github.com/luvit/luv

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
